import { useEffect } from "react";
import { Link } from "react-router-dom";
import {
  Sparkles,
  ArrowRight,
  Bot,
  FileText,
  Users,
  BarChart3,
  Code2,
  Briefcase,
  CheckCircle2,
  ArrowUpRight,
} from "lucide-react";
import { Container } from "@/components/container";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const ServicesPage = () => {
  useEffect(() => {
    const id = window.location.hash.slice(1);
    if (id) {
      setTimeout(
        () =>
          document
            .getElementById(id)
            ?.scrollIntoView({ behavior: "smooth", block: "start" }),
        50
      );
    }
  }, []);

  const services = [
    {
      id: "ai-mock-interviews",
      icon: Bot,
      title: "AI Mock Interviews",
      tagline: "Practice smarter, not harder.",
      description:
        "Unlimited tailored interviews generated by Google Gemini. Get instant AI feedback, a 1–10 rating, and actionable suggestions the moment you finish answering.",
      highlights: [
        "Role, stack, and seniority-specific questions",
        "Instant feedback with strengths & gaps",
        "Video on/off + live speech-to-text",
        "5 detailed Q&A per interview",
      ],
      cta: { label: "Start Practicing", to: "/generate" },
      accent: "from-indigo-500/15 to-violet-500/10",
      iconAccent: "bg-primary/10 text-primary",
    },
    {
      id: "resume-review",
      icon: FileText,
      title: "Resume Review",
      tagline: "Beat the ATS. Land more screens.",
      description:
        "AI-powered resume scoring with actionable line-by-line feedback. Check ATS compatibility, identify missing keywords, and tighten bullet points for maximum signal.",
      highlights: [
        "100-point ATS compatibility score",
        "Missing keyword & gap detection",
        "Bullet-point rewrite suggestions",
        "Formatting & layout recommendations",
      ],
      cta: { label: "Learn More", to: "/contact" },
      accent: "from-emerald-500/15 to-teal-500/10",
      iconAccent: "bg-success/15 text-success",
    },
    {
      id: "career-coaching",
      icon: Users,
      title: "Career Coaching",
      tagline: "A dedicated AI coach, always-on.",
      description:
        "Personalized guidance from your AI career coach. Define long-term goals, build a 6-month roadmap, negotiate offers, and navigate career pivots with data-backed advice.",
      highlights: [
        "Personalized 6-month growth roadmap",
        "Salary negotiation scripts & strategy",
        "Pivot planning for role transitions",
        "Goal tracking & weekly check-ins",
      ],
      cta: { label: "Get Started", to: "/signup" },
      accent: "from-amber-500/15 to-orange-500/10",
      iconAccent: "bg-amber-500/15 text-amber-600",
    },
    {
      id: "interview-analytics",
      icon: BarChart3,
      title: "Interview Analytics",
      tagline: "See your growth. Prove your progress.",
      description:
        "Detailed performance dashboards that track ratings over time, question category strengths and weaknesses, response length, filler words, and speech patterns.",
      highlights: [
        "Performance trendline over sessions",
        "Strengths / weaknesses breakdown",
        "Speech patterns & filler word analysis",
        "Exportable progress reports",
      ],
      cta: { label: "View Dashboard", to: "/generate" },
      accent: "from-sky-500/15 to-blue-500/10",
      iconAccent: "bg-sky-500/15 text-sky-600",
    },
    {
      id: "technical-interview-practice",
      icon: Code2,
      title: "Technical Interview Practice",
      tagline: "From DS&A to system design.",
      description:
        "Deep-dive practice for data structures, algorithms, system design, database modeling, API design, whiteboarding, and live problem-solving at FAANG difficulty.",
      highlights: [
        "DS&A arrays / trees / graphs / DP",
        "System design & scalability questions",
        "Database schema & API design drills",
        "Behavioral-technical hybrids",
      ],
      cta: { label: "Start Coding", to: "/generate" },
      accent: "from-violet-500/15 to-fuchsia-500/10",
      iconAccent: "bg-[#7C3AED]/15 text-[#7C3AED]",
    },
    {
      id: "hr-interview-practice",
      icon: Briefcase,
      title: "HR Interview Practice",
      tagline: "Tell your story flawlessly.",
      description:
        "Behavioral questions framed using the STAR method, culture-fit screens, salary negotiation, 'Why do you want to work here?' and every tough HR scenario in between.",
      highlights: [
        "STAR method structuring",
        "Culture & values fit questions",
        "Gap & weakness framing practice",
        "Negotiation & offer scripts",
      ],
      cta: { label: "Book a Consultation", to: "/contact" },
      accent: "from-rose-500/15 to-pink-500/10",
      iconAccent: "bg-rose-500/15 text-rose-600",
    },
  ];

  return (
    <div className="w-full">
      {/* Hero */}
      <Container className="pt-16 pb-12 md:pt-24 md:pb-16">
        <div className="max-w-4xl mx-auto text-center mb-12 md:mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 text-primary text-sm font-medium mb-8">
            <Sparkles className="w-4 h-4" />
            Services
          </div>
          <h1 className="text-4xl md:text-6xl lg:text-7xl font-extrabold tracking-tight text-foreground leading-[1.05] mb-6">
            Everything you need to{" "}
            <span className="text-gradient-primary">land your dream job</span>
          </h1>
          <p className="text-lg md:text-xl leading-relaxed text-muted-foreground max-w-2xl mx-auto mb-10">
            A complete end-to-end platform for interview preparation, career
            growth, and professional development. Pick one service or use them
            all — every tool is built to work together seamlessly.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link to="/contact">
              <Button size="lg" variant="outline">
                Book a Free Consultation
              </Button>
            </Link>
            <Link to="/generate">
              <Button size="lg">
                Start Practicing Now
                <ArrowRight className="w-4 h-4 ml-1" />
              </Button>
            </Link>
          </div>
        </div>
      </Container>

      {/* Services grid */}
      <Container className="pb-20 md:pb-28">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 md:gap-6">
          {services.map((svc) => {
            const Icon = svc.icon;
            return (
              <Card
                key={svc.id}
                id={svc.id}
                className="p-7 relative group overflow-hidden flex flex-col"
              >
                <div
                  className={`absolute inset-0 bg-gradient-to-br ${svc.accent} opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none`}
                />
                <div className="relative flex flex-col space-y-5 flex-grow">
                  <div className="flex items-start justify-between gap-4">
                    <div
                      className={`flex items-center justify-center w-12 h-12 rounded-2xl ${svc.iconAccent} transition-all duration-300 group-hover:scale-105`}
                    >
                      <Icon className="w-6 h-6" />
                    </div>
                    <Badge variant="outline" className="text-[11px]">
                      {svc.tagline}
                    </Badge>
                  </div>

                  <div className="space-y-2">
                    <h3 className="text-xl font-semibold tracking-tight text-foreground">
                      {svc.title}
                    </h3>
                    <p className="text-sm leading-relaxed text-muted-foreground">
                      {svc.description}
                    </p>
                  </div>

                  <ul className="space-y-2.5 pt-2">
                    {svc.highlights.map((h, i) => (
                      <li key={i} className="flex gap-2.5">
                        <div className="flex-shrink-0 mt-0.5">
                          <CheckCircle2 className="w-4 h-4 text-success" />
                        </div>
                        <span className="text-sm leading-relaxed text-foreground/80">
                          {h}
                        </span>
                      </li>
                    ))}
                  </ul>

                  <div className="pt-4 mt-auto">
                    <Link to={svc.cta.to}>
                      <Button
                        variant="ghost"
                        className="group/btn px-3 -ml-1 h-10 text-primary hover:text-primary hover:bg-primary/5"
                      >
                        {svc.cta.label}
                        <ArrowUpRight className="w-4 h-4 ml-1 transition-transform group-hover/btn:translate-x-0.5 group-hover/btn:-translate-y-0.5" />
                      </Button>
                    </Link>
                  </div>
                </div>
              </Card>
            );
          })}
        </div>
      </Container>

      {/* CTA Banner */}
      <Container className="pb-20 md:pb-28">
        <div className="relative overflow-hidden rounded-3xl border border-primary/10 bg-gradient-to-br from-[#7C3AED]/10 via-primary/5 to-transparent p-8 md:p-12 lg:p-14">
          <div className="absolute -top-24 -right-24 w-72 h-72 rounded-full bg-gradient-to-br from-primary/20 to-[#7C3AED]/20 blur-3xl pointer-events-none" />
          <div className="absolute -bottom-24 -left-24 w-72 h-72 rounded-full bg-gradient-to-br from-[#7C3AED]/20 to-primary/10 blur-3xl pointer-events-none" />
          <div className="relative max-w-3xl mx-auto text-center">
            <Badge
              variant="outline"
              className="px-3 py-1 mb-5 border-primary/30 text-primary bg-card/60 backdrop-blur"
            >
              <Sparkles className="w-3.5 h-3.5 mr-1.5 inline-block -mt-0.5" />
              Not sure which service fits?
            </Badge>
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight text-foreground mb-5">
              Let's build a plan that works for you
            </h2>
            <p className="text-base md:text-lg leading-relaxed text-muted-foreground mb-8 mx-auto max-w-2xl">
              Whether you're prepping for one specific role or building a
              long-term career growth strategy, our team can help tailor the
              perfect package. Reach out today — no pressure, just results.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link to="/contact">
                <Button size="lg">
                  Contact Our Team
                  <ArrowRight className="w-4 h-4 ml-1" />
                </Button>
              </Link>
              <Link to="/signup">
                <Button size="lg" variant="outline">
                  Create Free Account
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </Container>
    </div>
  );
};

export default ServicesPage;
